### PR TITLE
Send big output with file, updated text of request error

### PR DESCRIPTION
**Pull request by innocoffee-ftg**
...added backuper module as it's neccessary and also replaced tabs with spaces...

### CODE REVIEW

**Comment by Yahikoro** [comment]
@sourcery-ai[bot] @fast_geek гей

**Comment by gamedich** [comment]
@sourcery-ai[bot] Чееее

**Comment by Yahikoro** [comment]
@sourcery-ai[bot] бан

**Comment by fast-geek** [comment]
@Yahikoro лох

**Comment by gamedich** [comment]
@fast-geek Шипперим жизнь

**Pull request merged**
